try{
    hello();
} catch(error) {
    console.log('EL ERROR ES EL SIGUIENTE '+error+' JAJAJAJA');
}

try{
    anotherFn();
}catch{
    console.log('ESTO ES UN ERROR');
}